metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - filesystem
    - memory
    - network
    - process
  enabled: true
  period: 10s
  processes: ['.*']
  cpu_ticks: false
output.elasticsearch:
  # elastic instance url:port
  hosts: ["192.168.1.42:9200"]